version: 2

formats:
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true

mkdocs:
  configuration: mkdocs.yml

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
